### ISSUE TITLE
Injection at runtime

### ISSUE THREAD

**Issue by gedw99** [TomMannson/Finject#1]
Compile time injection looks very nicely done. 

Do you have any idea on runtime injection without requiring reflection.
The other way if to have compile time injection that respects build tags which I think would be awesome. The Dev passes in a tag at code gen time and it wires things up differently.
This would mean the annotation syntax would have to change to accomodate those tags.

What do you think ?

**Comment by TomMannson** [comment]
You are web or flutter developer?
For web I have no solution how to use my package at that moment.
This is dedicated package for flutter and is using generated code at runtime you can take a look here to see example:
https://github.com/TomMannson/Finject/blob/master/example/lib/main.dart
I am in progress of publish package finject_flutter to pub.

**Comment by gedw99** [comment]
Yes I am a flutter Dev.

I think you package as it is will work with Flutter Web because it's compile time and does not use reflection.

All I am suggesting it to add tags, so that as a developer I can wire up the same app different to allow using different ssrvices. At runtime.

Why is this useful. Well on larger apps you always hit the reusability wall and dependency wall. You might want one version of your app to use Google services and another to use onpremise services. Sure you can use interfaces and the factory pattern but what if you want to make sure there are no Google services in one version of your app anywhere in the code base that is deployed to users for security reasons.

Does that make sense now ?

**Comment by TomMannson** [comment]
I think that Profiles in springframework are some kind of tags, but my package is not supporting Profiles at that moment. 
But I think that's a good idea to implement it.

Connection of Profiles with build flavors can give good effect i development.
What you think?

**Comment by gedw99** [comment]
True it's like build flavours.

Personally I looked at them but steered away from that concrete coupling.

I would prefer is this tagging was not directly coupled. For instance I use flutter for web, desktop and mobile and flavours only work with mobile

**Comment by TomMannson** [comment]
One drawback of build_runner is that you can't pass custom parameters (tag) to process in other words I can't select tag in that way

I see this as some custom file extension like ".finject.enabletags.dart" for example in build time I'm scaning annotations with some Annotation like Profile or Tag.
Next step is filtring all Injectors which have diffrent tags then declarated in ".finject.enabletags.dart".
One problem with this solution is that you need to provide diffrent tag config for CI/CD

Maybe you have any idea where this tags can be hold, because for code generation I need some contract like Annotations and/or specific file extension to scan project and generate dependency graph

**Comment by gedw99** [comment]
Ah I see the problem.

Annotations in the code is exs fly how I would do it.
It's basically the same as build tags in golang.
Annotations can be is like "windows, android".
Or org names or any tag you want to invent.

But. Yes you have to pass in the takes to the code generator aka build_runner. I think you idea if a custom file extension is the best when we consider the tradeoffs. In fact I don't see any other option.

**Comment by gedw99** [comment]
I just realised how useful this is for i18n.
You can declare build tags and then only gen the country you need and not bloat your binary with all the others country.

Or for me the big one is injecting different GUI modules and sevices and routers for different countries. 

I use feature flags everywhere and so that is the opposite approach where you put lots of code into the binary but want to turn on / off certain GUI modules or services depending on diverse situations  it may be that I can use theze build tags to help control the default feature flags that are on / off based on if it canary, beta or stable versions I am pushing to users. It makes all the feature flags strongly typed basically and so makes all the code that has to check if s flag is switched on or off strongly typed.

Then from the feature flag server we can use those exact build tags like country , org, etc again to turn on certain features against users that have those build tags. Pretty nice.
I use a golang feature flag server and so can just parse the inject file for the build tags and feature flag tags in the git repo and use them 
So now your feature flag server uses the exact tags that are a really deployed at canary, beta or stable 
So now the feature flag server no longer holds the feature flag data but instead just an immutable log of the acknowledgement from the users of them recieving the event.

**Comment by TomMannson** [comment]
Hi, I produced some preview concept od profile feature. I need to test it a little bit but You can try it if you like.
https://github.com/TomMannson/Finject/tree/feature/profiles

**Comment by TomMannson** [comment]
Feature implemented
